/**
 * TypeScript 6 reports TS2882 for a side-effect import with no type
 * declarations, which catches `import './globals.css'` in the root layout.
 * Next.js compiles that import itself; these declarations just tell the
 * compiler the modules exist.
 *
 * `next-env.d.ts` does not cover it and is regenerated by Next on every
 * build, so the declarations live here instead.
 */

declare module '*.css';
declare module '*.scss';
declare module '*.sass';

declare module '*.module.css' {
  const classes: Record<string, string>;
  export default classes;
}

declare module '*.module.scss' {
  const classes: Record<string, string>;
  export default classes;
}
